# Generated by Django 5.1.6 on 2025-03-11 07:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('merged_documents', models.FileField(blank=True, null=True, upload_to='identity_documents/')),
                ('reason_for_admin_request', models.TextField()),
                ('past_experience', models.TextField()),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_address', models.TextField(blank=True, null=True)),
                ('emergency_contact_alternate_number', models.CharField(blank=True, max_length=15, null=True)),
                ('live_selfie_capture', models.ImageField(blank=True, null=True, upload_to='selfie_verification/')),
                ('signature_upload', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AdminVerifierUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="User's full name", max_length=255)),
                ('email', models.EmailField(help_text="User's email address", max_length=254, unique=True)),
                ('mobile_number', models.CharField(help_text='Mobile number with country code', max_length=15, unique=True)),
                ('street_address', models.CharField(help_text='Street address', max_length=255)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State', max_length=100)),
                ('is_volunteer', models.BooleanField(default=False, help_text='Flag to mark user as volunteer')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AdminGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text='Unique group name', max_length=255, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of creation')),
                ('admin', models.ForeignKey(help_text='Group admin', on_delete=django.db.models.deletion.CASCADE, related_name='admin_groups', to='core.adminuser')),
                ('allowed_volunteers', models.ManyToManyField(blank=True, help_text='Volunteers allowed in this group', related_name='accessible_groups', to='core.generaluser')),
            ],
        ),
        migrations.CreateModel(
            name='TodoTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='core.adminuser')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('completion_approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('assigned_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subtasks', to='core.generaluser')),
                ('todo_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.todotitle')),
            ],
        ),
    ]
