# Generated by Django 5.1.6 on 2025-03-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admingroups',
            name='city',
            field=models.CharField(default='Dindigul', help_text='City', max_length=100),
            preserve_default=False,
        ),
    ]
