# Generated by Django 5.1.6 on 2025-03-03 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminUser',
            new_name='AdminVerifierUser',
        ),
    ]
