# Generated by Django 5.1.6 on 2025-03-11 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_admingroups_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the volunteer request was made')),
                ('group', models.ForeignKey(help_text='Group for which the volunteer request is made', on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_requests', to='core.admingroups')),
                ('volunteer', models.ForeignKey(help_text='Volunteer user making the request', on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_requests', to='core.generaluser')),
            ],
        ),
    ]
