# Generated by Django 5.1.6 on 2025-03-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_adminuser_adminverifieruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('merged_documents', models.FileField(blank=True, null=True, upload_to='identity_documents/')),
                ('reason_for_admin_request', models.TextField()),
                ('past_experience', models.TextField()),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_relationship', models.CharField(max_length=100)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('emergency_contact_address', models.TextField()),
                ('live_selfie_capture', models.ImageField(blank=True, null=True, upload_to='selfie_verification/')),
                ('signature_upload', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('disaster_management_training_certificate', models.FileField(blank=True, null=True, upload_to='training_certificates/')),
                ('authorization_letter', models.FileField(blank=True, null=True, upload_to='authorization_letters/')),
            ],
        ),
    ]
