# Generated by Django 5.1.6 on 2025-03-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='authorization_letter',
            field=models.FileField(blank=True, null=True, upload_to='uploads/authorization_letters/'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='disaster_management_training_certificate',
            field=models.FileField(blank=True, null=True, upload_to='uploads/training_certificates/'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='live_selfie_capture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/selfie_verification/'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='merged_documents',
            field=models.FileField(blank=True, null=True, upload_to='uploads/identity_documents/'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='signature_upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/signatures/'),
        ),
    ]
