# Generated by Django 5.1.6 on 2025-03-11 23:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_volunteerrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrequests',
            name='address',
            field=models.TextField(default='123/TEMP, ABCD, DINDIGUL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerrequests',
            name='phone',
            field=models.CharField(default=9080380719, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerrequests',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_requests', to='core.admingroups'),
        ),
        migrations.AlterField(
            model_name='volunteerrequests',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='volunteerrequests',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_requests', to='core.generaluser'),
        ),
    ]
