# Generated by Django 5.1.6 on 2025-03-12 23:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_volunteerrequests_address_volunteerrequests_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text="Message type, e.g., 'text', 'image', 'video'", max_length=50)),
                ('content', models.TextField(help_text='Message content')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the message was sent')),
                ('group', models.ForeignKey(help_text='Group this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.admingroups')),
            ],
        ),
    ]
