# Generated by Django 5.1.6 on 2025-03-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adminuser_gender_adminuser_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='name',
            field=models.CharField(default='Santhosh', max_length=255),
            preserve_default=False,
        ),
    ]
