# Generated by Django 5.1.6 on 2025-03-04 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_adminuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='authorization_letter',
            field=models.FileField(blank=True, null=True, upload_to='authorization_letters/'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='disaster_management_training_certificate',
            field=models.FileField(blank=True, null=True, upload_to='training_certificates/'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='live_selfie_capture',
            field=models.ImageField(blank=True, null=True, upload_to='selfie_verification/'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='merged_documents',
            field=models.FileField(blank=True, null=True, upload_to='identity_documents/'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='signature_upload',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
